version: "3.8"
services:
    blog:
        image: localstradedocker/blog:blog_latest
        ports:
            - "8080:8080"
        depends_on:
            - mongodb
        environment:
            jwt512: ${jwt512}
            ssl_blog_passphrase: ${ssl_blog_passphrase}
            SPRING_PROFILES_ACTIVE: docker
            
    post:
        image: localstradedocker/blog:post_latest
        ports:
            - "8081:8080"
        depends_on:
            - postgres
        environment:
            jwt512: ${jwt512}
            ssl_blog_passphrase: ${ssl_blog_passphrase}
            SPRING_PROFILES_ACTIVE: docker
            
    postgres:
        image: postgres:15.4
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: posts
            POSTGRES_PASSWORD: admin
            
    postgres_blog:
        image: postgres:15.4
        container_name: postgres_blog
        ports:
        - "5433:5432"
        environment:
            POSTGRES_USER: blog
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: users
            
    mongodb:
        image: mongo:7.0
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: blog
            
    redis:
        image: "redis:latest"
        container_name: redis
        ports:
          - "6379:6379"