version: "1"
services:
    blog:
        container_name: blog
        build:
            context: ../monolith
            dockerfile: Dockerfile
        ports:
        - 8080:8080
        depends_on:
        - mongodb
        environment:
            SPRING_PROFILES_ACTIVE: docker
    post:
        container_name: post
        build:
            context: ../post
            dockerfile: Dockerfile
        ports:
        - 8081:8081
        depends_on:
        - postgres
        environment:
            SPRING_PROFILES_ACTIVE: docker
    postgres:
        image: postgres:15.4
        container_name: postgres
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: posts
            POSTGRES_PASSWORD: admin
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        ports:
        - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
    mongodb:
        image: mongo:7.0
        container_name: mongodb
        environment:
            MONGO_INITDB_DATABASE: blog
        ports:
            - 27017:27017  