version: "3.9"
services:
    blog:
        container_name: blog
        build:
            context: ../monolith
            dockerfile: Dockerfile
        ports:
        - "8080:8080"
        depends_on:
        - mongodb
        - postgres_blog
        environment:
            smtp_email: ${smtp_email}
            smtp_password: ${smtp_password}
            google_client_id: ${google_client_id}
            google_client_secret: ${google_client_secret}
            jwt512: ${jwt512}
            ssl_blog_passphrase: ${ssl_blog_passphrase}
            SPRING_PROFILES_ACTIVE: docker
            
    post:
        container_name: post
        build:
            context: ../post
            dockerfile: Dockerfile
        ports:
        - "8081:8080"
        depends_on:
        - postgres
        - minio
        environment:
            jwt512: ${jwt512}
            ssl_blog_passphrase: ${ssl_blog_passphrase}
            minio_password: ${minio_password}
            SPRING_PROFILES_ACTIVE: docker
            
    frontend:
        container_name: frontend
        build:
            context: ../frontend
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        volumes:
        - /app/node_modules/
        - /app/.next/
        - /app/app/
        environment:
            ssl_blog_passphrase: ${ssl_blog_passphrase} 
        
    postgres:
        image: postgres:15.4
        container_name: postgres
        ports:
        - "5432:5432"
        environment:
            POSTGRES_USER: posts
            POSTGRES_PASSWORD: admin
            
    postgres_blog:
        image: postgres:15.4
        container_name: postgres_blog
        ports:
        - "5433:5432"
        environment:
            POSTGRES_USER: blog
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: users
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
        - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            
    mongodb:
        image: mongo:7.0
        container_name: mongodb
        environment:
            MONGO_INITDB_DATABASE: blog
        ports:
            - "27017:27017"
            
    minio:
        image: minio/minio:RELEASE.2023-06-29T05-12-28Z.fips
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server --console-address ":9001" /data
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: ${minio_password}
        volumes:
            - /data
    
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        environment: 
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
            - "9300:9300"
        profiles: [debug]
      
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.1.1
        depends_on: 
            - elasticsearch
        ports:
            - "5044:5044"
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
            - ./logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
        profiles: [debug]
      
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.1.1
        depends_on:
            - elasticsearch
        ports: 
            - "5601:5601"
        profiles: [debug]            
            
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.35.0
        restart: unless-stopped
        ports:
            - "9090:9090"
        command:
            - "--config.file=/prometheus.yaml"
        volumes:
            - "./prometheus.yaml:/prometheus.yaml"
        profiles: [debug]            
      
    grafana:
        container_name: grafana
        image: grafana/grafana-oss:8.5.2
        restart: unless-stopped
        ports:
            - "3010:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_SERVER_DOMAIN=localhost
        profiles: [debug]