global:
  scrape_interval: 10m
  evaluation_interval: 10m


scrape_configs:
  - job_name: 'blog'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
      
  - job_name: 'post'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
      
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
