name: Monolith CI/CD
on:
 push:
    branches: [main]
 pull_request:
    branches: [main]
jobs:
  ship_container:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('GlobalTests/pom.xml')}}
        restore-keys: ${{runner.os}}-m2
    - name: Package
      run: mvn -B -f GlobalTests/pom.xml package
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKERHUBUSER}}
        password: ${{secrets.DOCKERHUB}}
        repository: localstradedocker/blog
        tags: globaltests_latest