name: GlobalTests CI/CD
on:
  push:
  repository_dispatch:
    types:
      - trigger_tests_monolith
      - trigger_tests_post
      - trigger_tests_security
jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    env:
        minio_password: ${{secrets.minio_password}}
        smtp_email: ${{secrets.smtp_email}}
        smtp_password: ${{secrets.smtp_password}}
        google_client_id: ${{secrets.google_client_id}}
        google_client_secret: ${{secrets.google_client_secret}}
        jwt512: ${{secrets.jwt512}}
        ssl_blog_passphrase: ${{secrets.ssl_blog_passphrase}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('GlobalTests/pom.xml')}}
        restore-keys: ${{runner.os}}-m2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    -
      name: Docker compose
      uses: isbang/compose-action@v1.5.1
      with:
          compose-file: ".github/docker-compose.yaml"
          down-flags: "--volumes"        
    - 
      name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    -
      name: Test
      run: mvn -B -f GlobalTests/pom.xml-Dssl_blog_passphrase=${{secrets.ssl_blog_passphrase}} -Dminio_password=${{secrets.minio_password}} test
    - 
      name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2